### ISSUE TITLE
This project has some security issues

### ISSUE THREAD

**Issue by blatyo** [wyeworks/elixir_console#24]
I can run unsafe commands like `File.write!/2`, `File.ls/1`, `File.read!/1`, and I can read environment variables that contain secrets with `System.get_env/1`. I can run arbitrary commands on the system with `System.cmd/2`. I can also shut down the application with `System.halt/1`.

I think this is a really cool project, but you really need a sandbox for this to be safe to run.

**Comment by jmbejar** [comment]
Just a quick note to say this aspect of the live console is still _in the making_.

We have worked on a mechanism to have a whitelist of allowed Elixir modules and Kernel functions, so we plan to support only a subset of Elixir.

Also, we added some logic to interrupt the execution of a command if it exceed limits on time and memory usage (it assumes we are not allowing to create processes due to the limited modules/functions the system will be exposing).

Nevertheless, we are still on research mode trying to find out whether it is really doable to implement a sandbox for Elixir, built in Elixir (without relying on more complicated infrastructure solutions, something we could extract to a package in the future). We're sure there should be more aspects to tackle, e.g. how to deal with abuse of atoms creation (since they are never garbage collected and global to the node).

**Comment by blatyo** [comment]
Yea, I have a feeling it's probably always going to have issues running in process. I expect you're trying to avoid what rust does for example and run things in a docker container.
https://github.com/integer32llc/rust-playground

I thought the ruby approach was actually pretty interesting, in that they use Opal to run ruby in the browser itself.
https://github.com/ruby/tryruby

That got me thinking maybe it would be possible to use something like lumen to build an interpreter that ran in the browser via web assembly.
https://github.com/lumen/lumen

**Comment by jmbejar** [comment]
> Yea, I have a feeling it's probably always going to have issues running in process. I expect you're trying to avoid what rust does for example and run things in a docker container.
> https://github.com/integer32llc/rust-playground

You're right, our goal is to have an Elixir sandbox written as a pure Elixir solution. I'm pretty confident it can be done by paying a little cost (not all Elixir functionality available and resources restrictions). I'm interested on this kind of solution because it could be easily available for the community (it will be a package, eventually). At the same time, I'm aware this is considered kind of impossible https://elixirforum.com/t/is-there-a-sandbox-mode-in-elixir/1715/4?u=jmbejar... so I just call it a research project for now 😄 

One import feature to preserve, if possible, is the idea of an interactive console, where you run commands, defining variables as you go, having the chance of using the bindings from previous commands. Eventually, if we are able to allow spawning processes in a safe way, the user could interact with those (I know we're still far from this reality, but I have some ideas). For those reasons, I'm still insisting on a solution that doesn't rely on Docker & friends (unless we can boot a docker instance per session, not one for each command). I also see a performance price with this approach, see https://github.com/integer32llc/rust-playground/issues/457

> 
> I thought the ruby approach was actually pretty interesting, in that they use Opal to run ruby in the browser itself.
> https://github.com/ruby/tryruby
> 
> That got me thinking maybe it would be possible to use something like lumen to build an interpreter that ran in the browser via web assembly.
> https://github.com/lumen/lumen

This is actually a very interesting idea. I have used Opal in the past, and it was a decent way to run Ruby in JS, so let's see how far Lumen goes given it is still in an early phase (as far I know). I agree this is an alternative if the Elixir pure solution is not possible at all.

**Comment by jmbejar** [comment]
Closing this issue because we addressed the mentioned issues in this report. Significant work has been done to have the first public release ready. We'll be doing the public announcement soon.

In case you found new security issues, please let us know following the instructions detailed in the Readme.

**Comment by jmbejar** [comment]
Closing this issue because we addressed the mentioned issues in this report. Significant work has been done to have the first public release ready. We'll be doing the public announcement soon.

In case you found new security issues, please let us know following the instructions detailed in the Readme.

**Comment by blatyo** [comment]
I tried reporting some more issues, but the email in the readme bounced.

**Comment by jmbejar** [comment]
> I tried reporting some more issues, but the email in the readme bounced.

@blatyo Hey, there was a mistake in the Readme. The proper email address is elixir-console-security@wyeworks.com.

I'm looking forward to seeing what you report.. thanks in advance for your help!
